using Microsoft.AspNetCore.WebUtilities;
using System.Security.Claims;
using AspNetAuth = Microsoft.AspNetCore.Authentication;

namespace BearerTokenBridge
{
    public static class MachineKeyOwinBearerAuthTicketUnprotector
    {
        /// <summary>
        /// Decodes, decryptes and seralizes a serialized, protected and encoded 
        /// AuthenticationTicket created by OWIN's OAuth server implementation.
        /// </summary>
        /// <param name="token">The token generated by OWIN (not not include 'bearer')</param>
        /// <param name="decryptionKey">The machineKey decryptionKey found in your web.config</param>
        /// <param name="validationKey">The machineKey validationKey found in your web.config</param>
        /// <returns>A v3 AuthenticationTicket</returns>
        public static AuthenticationTicket Unprotect(string token, string decryptionKey, string validationKey)
        {
            var decoded = WebEncoders.Base64UrlDecode(token);

            var unprotected = MachineKey.Unprotect(decoded, validationKey, decryptionKey, "User.MachineKey.Protect",
                "Microsoft.Owin.Security.OAuth", "Access_Token", "v1");

            var serializer = new TicketSerializer();
            var ticket = serializer.Deserialize(unprotected);
            return ticket;
        }

        /// <summary>
        /// Converts a v3 ticket to a v5.
        /// </summary>
        public static AspNetAuth.AuthenticationTicket Convert(AuthenticationTicket ticket, string authScheme)
        {
            var newTicket = new AspNetAuth.AuthenticationTicket(new ClaimsPrincipal(ticket.Identity),
                        ticket.Properties, authScheme);
            return newTicket;
        }
    }
}
